FROM node:7
ADD 1-2app.js /app.js
ENTRYPOINT ["node","app.js"]

#FROM defines base image
#ADD addes 1-2app.js from your local machine into root directory of container
#ENTRYPOINT defines what command should be executed when running this image


