apiVersion: apps/v1
kind: Deployment
metadata:
  name: migo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: migo
  template: 
    metadata:
      name: migo-pod
      labels:
        app: migo
    spec:
      containers:
      - image: saka1023/node_app:v1
        name: migo-con