apiVersion: v1
kind: Pod
metadata:
  name: migo-liveness
spec:
  containers:
    - image: saka1023/liveprobe
      name: migo-liveness
      livenessProbe:
        httpGet:
          path: /        
          port: 8080     
        initialDelaySeconds: 15
        periodSeconds: 5
        timeoutSeconds: 5