apiVersion: v1
kind: ReplicationController
metadata:
  name: migo-rc
spec:
  replica: 1
  selector:         # The pod selector determining what pods the RC is operating on
    app: migo-pod
  template:
    metadata:
      labels: 
        app: migo-pod
    spec:
      containers:
        - name: migo-con
          image: saka1023/k8s
          ports:
            - containerPort: 8080