apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
    - image: saka1023/kubia
      name: kubia
      ports:
        - containerPort: 8080
        #Specifying containerPort is purely informational. Omitting them has no effect
        #on whether client can connect to the pod through the pod or not.
        #If container is accepting connections through a port bound to 0.0.0.0 address,
        #other pods can always connect to it. 